# Generated by Django 3.2.12 on 2023-06-06 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='task_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_id',
        ),
        migrations.AlterField(
            model_name='subtask',
            name='parent_task',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='task.task'),
        ),
    ]
