# Generated by Django 3.2.12 on 2023-05-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.AlterField(
            model_name='subtask',
            name='task_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.IntegerField(),
        ),
    ]
