# Generated by Django 3.2.12 on 2023-05-31 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_remove_subtask_parent_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='parent_task',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='task.task'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('backlog', 'BackLog'), ('inprogress', 'Inprogress'), ('complete', 'Complete')], default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('backlog', 'BackLog'), ('inprogress', 'Inprogress'), ('complete', 'Complete')], default=True, max_length=100),
        ),
    ]
