# Generated by Django 4.2 on 2023-04-17 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_assigned_by_alter_task_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_by',
            field=models.ForeignKey(choices=[('ahmed', 'Ahmed'), ('kevin', 'Kevin'), ('kinya', 'Kinya')], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_assigned_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.BooleanField(choices=[('todo', 'Todo'), ('inprogress', 'Inprogress'), ('complete', 'Complete')], default=False),
        ),
    ]
